# Generated by Django 2.1.3 on 2018-11-15 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='age',
            field=models.CharField(choices=[('puppy', 'Puppy'), ('young', 'Young'), ('adult', 'Adult'), ('senior', 'Senior')], default='young', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dog',
            name='good_with_cats',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dog',
            name='good_with_dogs',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dog',
            name='good_with_kids',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dog',
            name='size',
            field=models.IntegerField(choices=[(1, 'Tiny'), (2, 'Small'), (3, 'Medium'), (4, 'Large')], default=1),
            preserve_default=False,
        ),
    ]
