# Generated by Django 2.1.3 on 2018-11-15 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_auto_20181115_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='img_filename',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
