# Generated by Django 2.1.3 on 2018-11-15 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0003_dog_img_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='picture',
            field=models.ImageField(null=True, upload_to='dogs/'),
        ),
    ]
