# Generated by Django 2.1.3 on 2018-11-15 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0004_dog_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dog',
            name='img_filename',
        ),
    ]
