# Generated by Django 2.1.3 on 2018-11-16 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0005_remove_dog_img_filename'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdoptionApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('current_pet_owner', models.BooleanField()),
                ('phone_number', models.CharField(max_length=30)),
                ('address1', models.CharField(max_length=255)),
                ('address2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('dog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets.Dog')),
            ],
        ),
    ]
